version: "3.9"

services:
  django:
    build:
      context: ./backend/newscout
      dockerfile: Dockerfile.dev
    container_name: newscout-backend
    working_dir: /workspace/backend/newscout

    entrypoint: ["/workspace/backend/newscout/entrypoint.sh"]

    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    ports:
      - "8000:8000"

    env_file:
      - ./backend/newscout/.env

    volumes:
      - .:/workspace

    depends_on:
      postgres:
        condition: service_started
      opensearch:
        condition: service_healthy

    networks:
      - app_net

  postgres:
    image: postgres:15
    container_name: newscout-db
    environment:
      POSTGRES_DB: newscout
      POSTGRES_USER: newscout
      POSTGRES_PASSWORD: newscout
    ports:
      - "5432:5432"
    volumes:
      - newscout_postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  opensearch:
    image: opensearchproject/opensearch:2.19.0
    container_name: newscout-opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - newscout_opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend/newscout
      dockerfile: Dockerfile.dev
    container_name: newscout-frontend
    working_dir: /workspace/frontend/newscout

    command: >
      sh -c "npm install && npm run dev"

    ports:
      - "3000:3000"

    volumes:
      - .:/workspace

    depends_on:
      - django

    networks:
      - app_net

volumes:
  newscout_postgres_data:
  newscout_opensearch_data:

networks:
  app_net:
    driver: bridge
