# Generated by Django 4.1 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_create_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
