import type { Metadata } from "next";
import { Inter, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/AppLayout";
import { Suspense } from "react";
import Loader from "@/app/loading";
import { ThemeProvider } from "next-themes";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system">
          <div className={`${inter.variable} ${dmSerif.variable} antialiased`}>
            <AppLayout>
              <Suspense fallback={<Loader />}>{children}</Suspense>
            </AppLayout>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
