 import { Comment } from "@/types/comment-types";
 export const dummyComments: Comment[] = [
  {
    id: "c1",
    author: "Sarah Mitchell",
    avatar: "SM",
    text: "This is a really insightful article. The way it breaks down the implications for policy makers is especially helpful. Looking forward to more coverage on this topic. I think the intersection of technology policy and economic reform is one of the most underreported areas in journalism today, and pieces like this really help bridge that gap for general readers.",
    time: "2 hours ago",
    likes: 14,
    dislikes: 1,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [
      {
        id: "c1r1",
        author: "James O'Brien",
        avatar: "JO",
        text: "Totally agree, Sarah. The policy angle is what makes this stand out from other coverage.",
        time: "1 hour ago",
        likes: 5,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
    ],
  },
  {
    id: "c2",
    author: "Alex Rivera",
    avatar: "AR",
    text: "I'd love to see more data on the economic impact. The article touches on it but doesn't go deep enough in my opinion.",
    time: "4 hours ago",
    likes: 8,
    dislikes: 2,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [],
  },
  {
    id: "c3",
    author: "Priya Sharma",
    avatar: "PS",
    text: "Great aggregation from multiple sources. This is exactly why I use NewScout — saves me from checking five different sites.",
    time: "6 hours ago",
    likes: 22,
    dislikes: 0,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [
      {
        id: "c3r1",
        author: "Tom Nguyen",
        avatar: "TN",
        text: "Same here! The source comparison feature is a game-changer.",
        time: "5 hours ago",
        likes: 7,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
      {
        id: "c3r2",
        author: "Elena Vogt",
        avatar: "EV",
        text: "Couldn't agree more. Multi-source news is the future.",
        time: "3 hours ago",
        likes: 3,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
    ],
  },
  {
    id: "c4",
    author: "Marcus Chen",
    avatar: "MC",
    text: "The geopolitical analysis here is spot on. I've been following this topic for months and this is one of the best summaries I've seen. What really stands out is how the author connects seemingly disparate events into a coherent narrative — from trade negotiations to defense spending shifts to the changing dynamics of multilateral institutions. This kind of holistic analysis is rare.",
    time: "8 hours ago",
    likes: 11,
    dislikes: 0,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [],
  },
  {
    id: "c5",
    author: "Laura Kim",
    avatar: "LK",
    text: "Would be great to see a follow-up piece on how this affects emerging markets specifically. Excellent reporting though!",
    time: "10 hours ago",
    likes: 6,
    dislikes: 1,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [
      {
        id: "c5r1",
        author: "David Okafor",
        avatar: "DO",
        text: "Seconded! The emerging market angle is often overlooked in mainstream coverage.",
        time: "9 hours ago",
        likes: 4,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
    ],
  },
  {
    id: "c6",
    author: "Rachel Thompson",
    avatar: "RT",
    text: "I shared this with my entire team. The clarity of writing here is exceptional — complex topics made accessible without dumbing them down.",
    time: "12 hours ago",
    likes: 18,
    dislikes: 0,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [],
  },
  {
    id: "c7",
    author: "Ahmed Hassan",
    avatar: "AH",
    text: "Finally a news platform that doesn't sensationalize everything. Keep up the great work NewScout!",
    time: "1 day ago",
    likes: 9,
    dislikes: 1,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [],
  },
];