 
export const DUMMY_COMMENTS: Comment[] = [
  {
    id: "c1",
    author: "Sarah Mitchell",
    avatar: "SM",
    text: "This is a really insightful article. The way it breaks down the implications for policy makers is especially helpful. Looking forward to more coverage on this topic.",
    time: "2 hours ago",
    likes: 14,
    dislikes: 1,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [
      {
        id: "c1r1",
        author: "James O'Brien",
        avatar: "JO",
        text: "Totally agree, Sarah. The policy angle is what makes this stand out from other coverage.",
        time: "1 hour ago",
        likes: 5,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
    ],
  },
  {
    id: "c2",
    author: "Alex Rivera",
    avatar: "AR",
    text: "I'd love to see more data on the economic impact. The article touches on it but doesn't go deep enough in my opinion.",
    time: "4 hours ago",
    likes: 8,
    dislikes: 2,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [],
  },
  {
    id: "c3",
    author: "Priya Sharma",
    avatar: "PS",
    text: "Great aggregation from multiple sources. This is exactly why I use NewScout — saves me from checking five different sites.",
    time: "6 hours ago",
    likes: 22,
    dislikes: 0,
    liked: false,
    disliked: false,
    showReplies: false,
    showReplyInput: false,
    replies: [
      {
        id: "c3r1",
        author: "Tom Nguyen",
        avatar: "TN",
        text: "Same here! The source comparison feature is a game-changer.",
        time: "5 hours ago",
        likes: 7,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
      {
        id: "c3r2",
        author: "Elena Vogt",
        avatar: "EV",
        text: "Couldn't agree more. Multi-source news is the future.",
        time: "3 hours ago",
        likes: 3,
        dislikes: 0,
        liked: false,
        disliked: false,
        replies: [],
        showReplies: false,
        showReplyInput: false,
      },
      
    ],
  },
];